config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :school_years do
    member do
      get :export
      put :change_school_year
      delete :delete_students
    end
  end
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'login', to: 'sessions#new', as: :login
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch :change_password
      end
    end
  resources :sessions, only: [:create]
  root to: 'main#home'
end

app/models/student.rb
class Student < ApplicationRecord
  include SoftDestroyable

  # -- Scopes
  default_scope { order(:gender, :last_name, :first_name)}
  scope :males, -> { where(gender: Student.genders[:male]) }
  scope :females, -> { where(gender: Student.genders[:female]) }

  # -- Enums
  enum gender: { male: 0, female: 1 }

  # -- Associations
  belongs_to :school_year

  # -- Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :dni, presence: true, length: { minimum: 8, maximum: 8 }
  validates :dni, uniqueness: true
  validates :dni, numericality: { only_integer: true }
  validates :gender, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @presenter = StudentsPresenter.new(params)
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to new_student_path, notice: 'El alumno se ha creado exitosamente'
    else
      flash[:error] = 'Ocurrió un error al crear el alumno. Por favor, intente nuevamente'
      render :new
    end
  end

  def update
    if @student.update(student_params)
      redirect_to students_path, notice: 'El alumno se ha modificado exitosamente.'
    else
      flash[:notice] = 'Ocurrió un error al modificar el alumno. Por favor, intente nuevamente'
      render :edit
    end
  end

  def destroy
    if @student.destroy
      flash[:notice] = 'El alumno se ha eliminado exitosamente'
    else
      flash[:notice] = 'Ocurrió un error al eliminar el alumno. Por favor, intente nuevamente'
    end
    redirect_to students_path
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:first_name, :last_name, :dni, :gender, :school_year_id)
  end
end

app/views/students/_filter.html.erb
<%= form_with model: @presenter.filter, url: students_path, method: :get, local: true do |f| %>
  <fieldset class="form-group col-md-3 col-xs-6 m-t">
      <%= f.text_field :name, placeholder: 'Nombre y/o apellido', class: 'form-control' %>
  </fieldset>

  <fieldset class="form-group col-md-2 col-xs-6 m-t">
      <%= f.text_field :dni, placeholder: 'DNI', class: 'form-control',
                       pattern: "([0-9]{8})", title: 'Ingresar los 8 dígitos' %>
  </fieldset>

  <fieldset class="form-group col-md-3 col-xs-6 m-t">
      <%= f.select :school_year_id,
                    SchoolYear.all.decorate.map { |school_year| [school_year.complete_name, school_year.id]},
                    {
                      include_blank: 'Seleccionar un grado'
                    },
                    id: :student_school_year,
                    class: 'form-control normal-select2',
                    data: {
                      placeholder: 'Seleccionar un grado'
                    }
      %>
  </fieldset>

  <fieldset class="form-group col-md-2 m-t">
    <%= f.check_box(:deleted) %>
    <%= label_tag(:deleted, "Ver eliminados") %>
  </fieldset>

  <div class="col-md-2 col-xs-4 m-t">
    <%= f.submit 'Buscar', class: 'btn btn-primary', 'data-disable-with' => 'Buscando...' %>
    <%= link_to students_path, class: 'btn btn-default', title: 'Reiniciar búsqueda' do %>
      <%= icon :undo %>
    <% end %>
  </div>
<% end %>

app/views/students/_form.html.erb
<% last_student = Student.last %>

<%= form_with(model: student, local: true) do |f| %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <fieldset class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name,
                          id: :student_first_name,
                          class: 'form-control',
                          required: true,
                          autofocus: true,
                          placeholder: 'Ingrese el nombre'
        %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name,
                          id: :student_last_name,
                          class: 'form-control',
                          required: true,
                          placeholder: 'Ingrese el apellido'
        %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :dni %>
        <%= f.number_field :dni,
                            id: :student_dni,
                            class: 'form-control',
                            required: true,
                            placeholder: 'Ingrese el DNI'
        %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :gender %>
        <%= f.select :gender,
                      Student.genders.map { |k, v| [t("student_genders.#{k}"), k]},
                      {
                        include_blank: 'Seleccionar un género' ,
                        selected: last_student.present? ? last_student.gender : nil
                      },
                      id: :student_gender,
                      class: 'form-control normal-select2',
                      required: true,
                      data: {
                        placeholder: 'Seleccionar un género'
                      }
        %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :school_year %>
        <%= f.select :school_year_id,
                      SchoolYear.all.decorate.map { |school_year| [school_year.complete_name, school_year.id]},
                      {
                        include_blank: 'Seleccionar un grado',
                        selected: last_student.present? ? last_student.school_year_id : nil
                      },
                      id: :student_school_year,
                      class: 'form-control normal-select2',
                      required: true,
                      data: {
                        placeholder: 'Seleccionar un grado'
                      }
        %>
      </fieldset>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group actions">
          <%= f.submit 'Guardar alumno', class: "btn btn-success" %>
          <%= link_to 'Volver', students_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_student.html.erb
<tr>
  <td><%= student.complete_name %></td>
  <td><%= student.dni %></td>
  <td><%= student.school_year_name %></td>
  <td>
    <%= link_to 'Editar', edit_student_path(student), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Eliminar', student, class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: "¿Realmente desea eliminar al alumno <b>#{student.complete_name}</b>?" } %>
  </td>
</tr>

app/views/students/edit.html.erb
<% provide(:title_header, 'Editar alumno')%>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Editar alumno</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
          <% end %>
      </li>
      <li>
        <%= link_to students_path do %>
          <%= fa_icon 'user', text: 'Alumnos' %>
          <% end %>
      </li>
      <li class="active">Editar alumno</li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body">
      <%= render 'form', student: @student %>
    </div>
  </div>
</section>

app/views/students/index.html.erb
<% provide(:title_header, 'Alumnos') %>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Alumnos</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
          <% end %>
      </li>
      <li class="active">Alumnos</li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body">
      <%= render 'filter' %>
    </div>
  </div>

  <div class="panel">
    <div class="panel-body responsive-table">
      <%= link_to new_student_path ,
            title: 'Nuevo alumno',
            class: 'panel-main-action btn btn-warning btn-rounded' do %>
        <%= fa_icon 'plus' %>
      <% end %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>DNI</th>
            <th>Grado</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @presenter.students %>
        </tbody>
      </table>

      <%= paginate @presenter.students, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm no-margin pull-right" %>

      <% if @presenter.students.empty? %>
        <p class="lead text-center"> Nada que mostrar por aquí </p>
      <% end %>

    </div>
  </div>
</section>

app/views/students/new.html.erb
<% provide(:title_header, 'Nuevo alumno')%>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Nuevo alumno</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
          <% end %>
      </li>
      <li>
        <%= link_to students_path do %>
          <%= fa_icon 'user', text: 'Alumnos' %>
          <% end %>
      </li>
      <li class="active">Nuevo alumno</li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body">
      <%= render 'form', student: @student %>
    </div>
  </div>
</section>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @student.dni %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @student.gender %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>