config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :school_years do
    member do
      get :export
      put :change_school_year
      delete :delete_students
    end
  end
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'login', to: 'sessions#new', as: :login
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch :change_password
      end
    end
  resources :sessions, only: [:create]
  root to: 'main#home'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  # -- Validations
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true,
                       if: -> { new_record? || changes[:crypted_password] }
  validates :password, length: { minimum: 8 },
                       if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true,
                       if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true,
                       if: -> { new_record? || changes[:crypted_password] }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy change_password]

  def index
    authorize User
    @users = User.all.page(params[:page])
  end

  def new
    authorize User
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      redirect_to users_path, notice: '¡El usuario se creó exitosamente!'
    else
      flash[:error] = '¡Ups! Hubo un error al intentar crear el usuario.'
      render 'new'
    end
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to root_path, notice: '¡El usuario se modificó exitosamente!'
    else
      flash[:error] = '¡Ups! Hubo un error al intentar modificar el usuario.'
      render :edit
    end
  end

  def change_password
    authorize @user
    if @user.valid_password? params[:user][:current_password]
      if @user.update(user_params)
        redirect_to root_path, notice: t(:success)
      else
        flash[:error] = '¡Ups! No se ha podido cambiar la clave.
                        Por favor intente nuevamente'
        render :edit
      end
    else
      @user.errors[:current_password] << 'La clave actual es incorrecta'
      render :edit
    end
  end

  def destroy
    authorize @user
    if @user.destroy
      redirect_to users_path, notice: t(:success)
    else
      flash[:error] = '¡Ups! No se ha podido eliminar el usuario.
                      Por favor intente nuevamente'
      redirect_to time_records_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <fieldset class="form-group">
        <%= f.label :email %>
        <% if user.persisted? %>
          <code><%= user.email %></code>
        <% else %>
          <%= f.email_field :email, placeholder: 'Email', class: 'form-control', required: true %>
        <% end %>
      </fieldset>

      <fieldset class="form-group">
       <%= f.label :password %><br />
       <%= f.password_field :password, placeholder: 'Contraseña', class: 'form-control' %>
      </fieldset>

      <fieldset class="form-group">
         <%= f.label :password_confirmation %><br />
         <%= f.password_field :password_confirmation, placeholder: 'Confirme contraseña', class: 'form-control', required: true %>
      </fieldset>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group actions">
        <%= f.submit 'Guardar Usuario', class: "btn btn-success", data: 
          { 'disable-with' => 'Guardando...' } %>
          <%= link_to 'Volver', :back, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for @user do |f| %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <fieldset class="form-group">
        <%= f.label :email %>
        <code><%= @user.email %></code>
      </fieldset>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group actions">
        <%= f.submit 'Guardar Usuario', class: 'btn btn-success',
          data: { 'disable-with' => 'Espere...' } %>
          <%= link_to 'Volver', :back, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form_password.html.erb
<%= form_for @user, url: change_password_user_path do |f| %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <fieldset class="form-group">
       <%= f.label :current_password, 'Clave actual' %><br />
       <%= f.password_field :current_password, placeholder: 'Clave actual', class: 'form-control', required: true %>
      </fieldset>

      <fieldset class="form-group">
       <%= f.label :password, 'Nueva clave' %><br />
       <%= f.password_field :password, placeholder: 'Nueva clave', class: 'form-control', required: true %>
      </fieldset>

      <fieldset class="form-group">
         <%= f.label :password_confirmation %><br />
         <%= f.password_field :password_confirmation, placeholder: 'Confirmación de clave', class: 'form-control', required: true %>
      </fieldset>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group actions">
          <%= f.submit 'Cambiar clave', class: "btn btn-success", 'data-disable-with' => 'Cambiando clave...' %>
          <%= link_to 'Volver', :back, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr id="<%= dom_id(user) %>">
  <td><%= link_to user.email, edit_user_path(user) %></td>
  <td>
    <% if policy(user).destroy? %>
      <%= link_to user, method: :delete, title: 'Eliminar usuario',
          data: { title:'Cuidado', confirm: "Estás a punto de eliminar al usuario <strong>#{user.email}</strong>. Esta acción no puede deshacerse. ¿Estás seguro?", 'confirm-btn' => 'Si, eliminar usuario', 'cancel-btn' => 'No, cancelar'},
          class: 'btn btn-xs btn-danger js-delete-user' do %>
          <%= icon :trash %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/users/edit.html.erb
<% provide(:title_header, 'Editar usuario')%>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Editar perfil</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Home' %>
        <% end %>
      </li>
      <li class="active">Editar perfil</li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-md-6">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Datos personales</h5>
        </div>
        <div class="ibox-content">
          <%= render 'form_edit', user: @user %>
        </div>
      </div>
    </div>
    <% if policy(@user).change_password? %>
      <div class="col-md-6">
        <div class="ibox">
          <div class="ibox-title">
            <h5>Cambio de clave</h5>
          </div>
          <div class="ibox-content">
            <%= render 'form_password', user: @user %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title_header, 'Usuarios')%>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Administración de Usuarios</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Home' %>
        <% end %>
      </li>
      <li class="active">Usuarios</li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body responsive-table">
      <%= link_to new_user_path,
            title: 'Nuevo usuario',
            class: 'panel-main-action btn btn-warning btn-rounded' do %>
        <%= fa_icon 'plus' %>
      <% end %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Email</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>

      <%= paginate @users, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm no-margin pull-right" %>

      <% if @users.empty? %>
        <p class="lead text-center">No hay usuarios para mostrar</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title_header, 'Nuevo usuario')%>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Nuevo usuario</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Home' %>
        <% end %>
      </li>
      <li>
        <%= link_to users_path do %>
          <%= fa_icon 'user', text: 'Usuarios' %>
        <% end %>
      </li>
      <li class="active">Nuevo usuario</li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body">
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>