config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :school_years do
    member do
      get :export
      put :change_school_year
      delete :delete_students
    end
  end
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'login', to: 'sessions#new', as: :login
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch :change_password
      end
    end
  resources :sessions, only: [:create]
  root to: 'main#home'
end

app/models/school_year.rb
class SchoolYear < ApplicationRecord

  # -- Associations
  has_many :students

  # -- Scopes
  default_scope { order(:level, :name)}

  # -- Enums
  enum level: %i[initial primary secondary]

  # -- Validations
  validates :name, presence: true
  validates :name, uniqueness: { scope: [:level] }
  validates :level, presence: true
end

app/controllers/school_years_controller.rb
class SchoolYearsController < ApplicationController
  before_action :set_school_year, only: [:show, :edit, :update, :destroy, :export, :change_school_year, :delete_students]
  before_action :set_school_year_decorate, only: [:export]

  def index
    @school_years = SchoolYear.all.page(params[:page]).decorate
  end

  def show
    @presenter = SchoolYearPresenter.new(@school_year)
  end

  def new
    @school_year = SchoolYear.new
  end

  def edit
  end

  def create
    @school_year = SchoolYear.new(school_year_params)

    if @school_year.save
      redirect_to school_years_path, notice: 'El grado se ha creado exitosamente.'
    else
      flash[:error] = 'Ocurrió un error al crear el curso. Por favor, intente nuevamente'
      render :new
    end
  end

  def update
    if @school_year.update(school_year_params)
      redirect_to school_years_path, notice: 'El grado se ha modificado exitosamente.'
    else
      flash[:error] = 'Ocurrió un error al modificar el grado. Por favor, intente nuevamente'
      render :edit
    end
  end

  def destroy
    if @school_year.destroy
      flash[:notice] = 'El grado se ha eliminado exitosamente'
    else
      flash[:error] = 'Ocurrió un error al eliminar el grado. Por favor, intente nuevamente'
    end
    redirect_to school_years_path
  end

  def export
    render xlsx: 'export',
           filename: "#{@school_year.complete_name}.xlsx",
           locals: {xlsx_use_shared_strings: true}
  end

  def change_school_year
    student_ids = params[:school_year][:student_ids].reject(&:blank?)
    school_year_id = params[:school_year_id]
    if Student.where(id: student_ids).update(school_year_id: school_year_id)
      flash[:notice] = 'Los alumnos se cambiaron de grado exitosamente'
    else
      flash[:error] = 'Ocurrió un error al cambiar a los alumnos de grado. Por favor, intente nuevamente'
    end
    redirect_to @school_year
  end

  def delete_students
    student_ids = params[:school_year][:student_ids].reject(&:blank?)
    if Student.where(id: student_ids).update(deleted_at: Time.now)
      flash[:notice] = 'Los alumnos se sacaron del grado exitosamente'
    else
      flash[:error] = 'Ocurrió un error al sacar a los alumnos de grado. Por favor, intente nuevamente'
    end
    redirect_to @school_year
  end

  private

  def set_school_year
    @school_year = SchoolYear.find(params[:id])
  end

  def set_school_year_decorate
    @school_year = @school_year.decorate
  end

  def school_year_params
    params.require(:school_year).permit(:name, :level, :student_ids)
  end
end

app/views/school_years/_form.html.erb
<%= form_with(model: school_year, local: true) do |f| %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <fieldset class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name,
                          id: :school_year_name,
                          class: 'form-control',
                          required: true,
                          autofocus: true,
                          placeholder: 'Ingrese un nombre'
        %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :level %>
        <%= f.select :level,
                      SchoolYear.levels.map { |k, v| [t("school_year_levels.#{k}"), k]},
                      { include_blank: 'Seleccionar un nivel' },
                      id: :school_year_level,
                      class: 'form-control normal-select2',
                      required: true,
                      data: { placeholder: 'Seleccionar un nivel' }
        %>
      </fieldset>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group actions">
          <%= f.submit 'Guardar grado', class: "btn btn-success" %>
          <%= link_to 'Volver', school_years_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/school_years/_school_year.html.erb
<tr>
  <td>
    <%= link_to school_year.name,
                school_year_path(school_year),
                title: 'Ver detalles del grado'
    %>
  </td>
  <td><%= school_year.level_name %></td>
  <td>
    <%= link_to 'Editar',
                edit_school_year_path(school_year),
                class: 'btn btn-xs btn-primary'
    %>
    <%= link_to 'Eliminar',
                school_year,
                class: 'btn btn-xs btn-danger',
                method: :delete,
                data: { confirm: "¿Realmente desea eliminar el grado <b>#{school_year.complete_name}</b>?" }
    %>
  </td>
</tr>

app/views/school_years/_student.html.erb
<tr>
  <td>
    <input type="checkbox" name="" value="" class="js-student-check" data-student-id="<%= student.id %>">
  </td>
  <td><%= student.last_name %></td>
  <td><%= student.first_name %></td>
  <td><%= student.dni %></td>
</tr>

app/views/school_years/edit.html.erb
<% provide(:title_header, 'Editar grado')%>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Editar grado</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
          <% end %>
      </li>
      <li>
        <%= link_to school_years_path do %>
          <%= fa_icon 'graduation-cap', text: 'Grados' %>
          <% end %>
      </li>
      <li class="active">Editar grado</li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body">
      <%= render 'form', school_year: @school_year %>
    </div>
  </div>
</section>

app/views/school_years/index.html.erb
<% provide(:title_header, 'Grados') %>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Grados</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
          <% end %>
      </li>
      <li class="active">Grados</li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body responsive-table">
      <%= link_to new_school_year_path ,
            title: 'Nuevo grado',
            class: 'panel-main-action btn btn-warning btn-rounded' do %>
        <%= fa_icon 'plus' %>
      <% end %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Nivel</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @school_years %>
        </tbody>
      </table>

      <%= paginate @school_years, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm no-margin pull-right" %>

      <% if @school_years.empty? %>
        <p class="lead text-center"> Nada que mostrar por aquí </p>
      <% end %>

    </div>
  </div>
</section>

app/views/school_years/new.html.erb
<% provide(:title_header, 'Nuevo grado')%>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Nuevo grado</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
          <% end %>
      </li>
      <li>
        <%= link_to school_years_path do %>
          <%= fa_icon 'graduation-cap', text: 'Grados' %>
          <% end %>
      </li>
      <li class="active">Nuevo grado</li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body">
      <%= render 'form', school_year: @school_year %>
    </div>
  </div>
</section>

app/views/school_years/show.html.erb
<% provide(:title_header, 'Detalle del grado')%>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Detalle del grado</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
        <% end %>
      </li>
      <li>
        <%= link_to school_years_path do %>
          <%= fa_icon 'graduation-cap', text: 'Grados' %>
        <% end %>
      </li>
      <li class="active">Detalle del grado - <%= @presenter.school_year_decorated.complete_name %></li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="ibox">
    <div class="ibox-content">
      <h2 class="text-center font-bold"><%= @presenter.school_year_decorated.complete_name %></h2>

      <br>

      <% if @presenter.has_students? %>
        <div class="row">
          <div class="col-md-12">
            <%= form_with model: @presenter.school_year, url: change_school_year_school_year_path(@presenter.school_year), method: :put, local: true do |f| %>
              <div class="col-md-2">
                <input type="checkbox" name="" value="" id="js-select-all" style="margin-bottom: 2%;"> Seleccionar todos
              </div>
              <div class="col-md-4">
                <fieldset class="form-group">
                  <%= select_tag :school_year_id,
                                options_from_collection_for_select(
                                  SchoolYear.where.not(id: @presenter.school_year.id).decorate, 'id', 'complete_name'
                                ),
                                id: :student_school_year,
                                class: 'form-control normal-select2',
                                required: true,
                                include_blank: 'Seleccionar un grado',
                                data: {
                                  placeholder: 'Seleccionar un grado'
                                }
                  %>
                </fieldset>
              </div>
              <div class="col-md-3">
                <%= f.select :student_ids, {}, {}, multiple: true, class: 'hidden js-student-ids' %>

                <%= f.submit 'Cambiar de curso', class: 'btn btn-md btn-primary js-student-action' %>
              </div>
              <% end %>
              <div class="col-md-3">
                <%= form_with model: @presenter.school_year, url: delete_students_school_year_path(@presenter.school_year), method: :delete, local: true do |form| %>
                  <%= form.select :student_ids, {}, {}, multiple: true, class: 'hidden js-student-ids' %>
                  <%= form.submit 'Sacar del curso', class: 'btn btn-md btn-danger text-right js-student-action' %>
                <% end %>
              </div>
          </div>
        </div>
      <% end %>

      <br>

      <% unless @presenter.has_students? %>
        <p class="lead text-center"> Nada que mostrar por aquí </p>
      <% else %>
        <div class="row">
          <% unless @presenter.male_students.empty? %>
            <div class="col-md-6">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th></th>
                    <th>Apellido</th>
                    <th>Nombre</th>
                    <th>DNI</th>
                  </tr>
                </thead>

                <tbody>
                  <%= render partial: 'student', collection: @presenter.male_students.decorate, as: :student %>
                </tbody>
              </table>
            </div>
          <% end %>

          <% unless @presenter.female_students.empty? %>
            <div class="col-md-6">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th></th>
                    <th>Apellido</th>
                    <th>Nombre</th>
                    <th>DNI</th>
                  </tr>
                </thead>

                <tbody>
                  <%= render partial: 'student', collection: @presenter.female_students.decorate, as: :student %>
                </tbody>
              </table>
            </div>
          <% end %>
      </div>
      <% end %>
    </div>
    <div class="ibox-footer">
      <div class="row">
        <div class="col-md-9 col-md-offset-3">
          <div class="form-group actions">
            <%= link_to 'Exportar a Excel',
                        export_school_year_path(@presenter.school_year, format: :xlsx),
                        class: 'btn btn-md btn-info pull-right'
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>