config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :school_years do
    member do
      get :export
      put :change_school_year
      delete :delete_students
    end
  end
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'login', to: 'sessions#new', as: :login
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch :change_password
      end
    end
  resources :sessions, only: [:create]
  root to: 'main#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :require_login

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  NOT_AUTHORIZED = 'No tenés los permisos necesarios para realizar esta acción.'.freeze
    NOT_AUTHENTICATED = 'Debes iniciar sesión para acceder a esta página.'.freeze

    def not_authenticated
      redirect_to login_path, alert: 'Por favor, inicia sesión.'
    end


  def user_not_authorized
    respond_to do |format|
      format.html do
        flash[:error] = NOT_AUTHORIZED
        redirect_to root_path
      end
      format.js do
        render json: { msg: NOT_AUTHORIZED }, status: :forbidden
      end
    end
  end

end

app/helpers/application_helper.rb
# application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  def flash_message(type, message)
    toast_type = ''
    toast_type += 'success' if ['success', 'notice'].include? type
    toast_type += 'error'  if ['error', 'danger'].include? type
    toast_type += 'warning' if type == 'warning'
    flash.discard(type)
    toast = "<script>App.showToastr('#{toast_type}', '#{message}');</script>"
    toast.html_safe
  end

  def full_title(page_title)
    base_title = I18n.t :app_name
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def flash_messages
    messages = []
    flash.each do |type, message|
      messages << flash_message(type, message) if message
    end
    messages.join('/n').html_safe
  end

  def close_button(target = :modal)
    link_to '&times;'.html_safe, '', class: :close, data: { dismiss: target }
  end

  def icon(name, html_options = {})
    html_options[:class] = ['fa', "fa-#{name}", html_options[:class]].compact
    content_tag(:i, nil, html_options)
  end

  # Link del menú lateral
  def side_link(text: '', path: '', icon_class: '', klass: '',
                html_options: {}, extra: '')
    link_class = html_options[:class]
    html_options[:class] = link_class
    klass += current_page?(path) ? 'active' : url_for(path)
    content_tag(:li, class: klass) do
      (link_to path, html_options do
        "<i class='fa fa-fw fa-#{icon_class}'></i> <span> #{text} </span>".html_safe
      end) +
        extra.html_safe
    end
  end

  def side_link_status(controller_names_array, class_name = nil)
    if controller_names_array.include?(params[:controller])
      class_name || 'active'
    else
      nil
    end
  end

  def sidebar_state
    'mini-navbar' if content_for :hide_sidebar
  end

  def sub_menu(klass = '', &block)
    klass += ' ' if klass.present?
    klass += 'treeview-menu'
    tree = ''

    if block_given?
      tree = content_tag(:ul, class: klass) do
        capture(&block)
      end
    end

    tree
  end

  def back_to_link(link_text, link_path = '', klass = '', html_options = {})
    link_path = 'javascript:history.back()' if link_path.blank?
    content_tag(:div, class: 'return-back ' + klass) do
      link_to(link_path, options: {}, html_options: html_options) do
        icon('angle-left').html_safe +
          "<span> #{link_text} </span>".html_safe
      end
    end
  end
end

app/views/application/_aside.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
          <li class="nav-header">
            <span class="logo-mini"><b>A</b></span>
            <span class="logo-lg"><b>Alumnos</b></span>
          </li>
          <%= side_link text: 'Inicio', path: root_path, icon_class: 'home' %>
          <%= side_link text: 'Grados', path: school_years_path, icon_class: 'graduation-cap' %>
          <%= side_link text: 'Alumnos', path: students_path, icon_class: 'user' %>
        </ul>
    </div>
</nav>

app/views/application/_head.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= csrf_meta_tags %>

<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

app/views/application/_navbar.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#">
        <i class="fa fa-bars"></i>
      </a>
    </div>
      <% if logged_in? %>
      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <%= current_user.email %>
            </span><b class="caret"></b>
            </span>
          </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li>
              <%= link_to 'Editar perfil', [:edit, current_user] %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Cerrar sesión', logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    <% end %>
</nav>
</div>